#!/bin/bash
current_directory=$(pwd)

cd $current_directory/final_analysis/
for item in *.fastq
do
    centrifuge -p 4 -k 50 -q -x vert_virusALL_08122022_GRCg7b_index -S "${item:0:4}"_report.csv --report-file "${item:0:4}"_report.tsv $item
done
awk -F'\t' '$1 ~ /Gallid alphaherpesvirus 1|herpesvirus/ {print $2}' *_report.tsv > ILTV_TaxID.txt
for c in *.csv 
do
	awk 'NR == FNR {
		 patt[$0]; next
		}
	{
        for (p in patt)
        	if ($3 ~ p) print $1
            }' ILTV_TaxID.txt $c > "${c:0:4}"_ILTV_ReadIDs.txt   
done

if [ ! -d for_geneous ]
then
    mkdir for_geneous
elif [ -d for_geneous ]
then 
	for Read in *_ReadIDs.txt
	do 
		grep -A3 -f $Read "${Read:0:4}".fastq > "${Read:0:-4}".fq
		grep -v -Fx -- -- "${Read:0:-4}".fq > "${Read:0:-4}".fastq
        sequences=$(grep -o "read" "${Read:0:-4}".fastq | wc -l)
		echo "${Read:0:-4} $sequences" >> for_geneous/output_num.txt
		mv "${Read:0:-4}".fastq for_geneous/.
	done
fi
